# Generated by Django 3.1.1 on 2020-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20201004_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_datetime',
            field=models.DateTimeField(verbose_name='notification date and time '),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_datetime',
            field=models.DateTimeField(verbose_name='creating date and time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='text description of title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='task title'),
        ),
    ]
