# Generated by Django 3.1.1 on 2020-11-01 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20201006_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_datetime',
            field=models.DateTimeField(verbose_name='notification date and time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Description of title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Task title'),
        ),
    ]
